### ISSUE TITLE
Project types / capabilities

### ISSUE THREAD

**Issue by jedwood** [presidential-innovation-fellows/rfpez#98]
Casting my vote for a super-simplified set of categories for both project types and vendor capabilities, given the small scope of our pilot. It's easy to add more if/when the day comes. Hitting a middle ground with this stuff seems tricky. For example, "Content Management" doesn't really matter- what matters is whether you know Drupal or WordPress. So rather than an extensive list, something like:
- Design
- Development
- Video

Or maybe
- Graphic Design
- Front-end development 
- Back-end development 
- Video Production

/cc @cjoh @adamjacobbecker

**Comment by NICFederal** [comment]
I notice that the application/tasks/seed.php are NAICS code based and I think web design, CMSs, and (my favorite)  transaction funded web design all come under 541511.  One idea to keep this NAICS based but still clear would be two levels:
541511: Custom Computer Programming Services
- web design
- transaction funded web design
- CMS

541430: graphic design

511210: software publishers
- back-end development
- iPhone app
- android app

**Comment by jedwood** [comment]
@NICFederal thanks for jumping in! Just to clarify, our primary goal is to make it such that the NAICS codes don't even appear to businesses. We're also still thinking through whether to even have businesses specify what their capabilities are.

**Comment by NICFederal** [comment]
My apologies, I am referring to the SOW Composer for procurement officers.  My hope is that the procurement side, though SOW Composer, would be able to specify NAICS numbers and further clarify their needs (like web design, transaction funded web design, CMS) for the outgoing (meaning federal government to vendors) RFI/RFP.

**Comment by ajb** [comment]
Ah, got it. I think we've also gotta make the distinction between program officers and contracting/procurement officers, since the PO will probably not be looking for a category by NAICS code, whereas the CO would.

It also helps that this pilot is limited to < 10 NAICS codes in total, but if/when it expands we'll definitely need to rethink how we classify the projects in the system.

For now, it's probably easiest for us to just create categories for each of the procurements we're running in the pilot. I just opened GH-106 and I'll close this ticket.
